name = "Minecraft Client 1 . 20 . 4 Vanilla Modpack"
author = "Nic4Las"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b9b2752cc9eb7abe6e2284a9b3f80935963beefa2c27fa90c5f7b56a14e7498"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
